import type { NextPage } from "next";
import dynamic from "next/dynamic";
import Head from "next/head";
import { useAuth, useUser } from "../lib/auth";
import styles from "../styles/Home.module.css";

const DraggableUploader = dynamic(
  () => import("../components/ad/DraggableUploader"),
  { ssr: false }
);

const Home: NextPage = () => {
  useAuth({ redirectTo: "/login" });
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <DraggableUploader />
      </main>
    </div>
  );
};

export default Home;
