import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { useAuth } from "../lib/auth";
import { initializeGraphQL } from "../lib/graphql-client";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  const { isSignedIn } = useAuth();
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {isSignedIn() ? (
          <>
            <Link href={"/add"}>Add</Link>
            <br />
            <Link href={"/logout"}>Logout</Link>
          </>
        ) : (
          <>
            <Link href={"/login"}>Login</Link>
            <br />
            <Link href={"/register"}>Register</Link>
          </>
        )}

        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>
      </main>
    </div>
  );
};

export default Home;

export async function getServerStaticProps() {
  const client = initializeGraphQL();

  // await Promise.all([
  //   graphQLRequest(client, TEST_LIST_QUERY),
  //   graphQLRequest(client, TEST_ITEM_QUERY)
  // ]);

  return {
    props: {
      initialGraphQLState: client.cache.getInitialState()
    },
    revalidate: 1
  };
}
