import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Router from "next/router";
import { useCookies } from "react-cookie";
import LoginComponent from "../components/user/LoginComponent";
import config from "../lib/config";
import styles from "../styles/Home.module.css";

const Login: NextPage = () => {
  const [cookies] = useCookies([config.userTokenStoreName]);
  if (cookies[config.userTokenStoreName]) {
    console.log(
      "cookies[config.userTokenStoreName]",
      cookies[config.userTokenStoreName]
    );
    Router.push("/");
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <LoginComponent />
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Login;
